#version: "3.8"

services:
  bot:
    build: .
    container_name: bot_prod
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped


  db:
    image: postgres:15
    container_name: db_prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
