#version: "3.8"

services:
  bot:
    build: 
      context: ../
      dockerfile: Dockerfile
    container_name: bot_dev
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped


  db:
    image: postgres:15
    container_name: db_dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always


go-service:
    build:
      context: ./go-service  
      dockerfile: Dockerfile  
    container_name: go_service_dev
    environment:
      - INTERNAL_TOKEN=${INTERNAL_TOKEN}   
    ports:
      - "8080:8080"    
    restart: unless-stopped


volumes:
  pgdata:
